apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: image-classifier
  labels:
    app: image-classifier
    component: metrics
spec:
  selector:
    app: image-classifier
  ports:
  - name: metrics
    port: 8001
    targetPort: 8001 